# The file must start with `version: 2`
version: 2
updates:
  # Enable version updates for npm / yarn
  # The 'npm' value is suitable for both npm and yarn package managers
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every monday
    schedule:
      interval: "monthly"
    # Raise pull requests to update the `dev` branch
    target-branch: "master"
